/*
  Anti-Crook Bag: A secure backpack that alarms as a theft detterent.
  Copyright (C) 2026 Jonas Blackwood, Malachi Oldham, Jesse Sivils

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/* 
  Auth.h
  ---------------------
  Written by Jonas Blackwood
  Some KVStore code generated by ChatGPT
*/

#ifndef AUTH_H
#define AUTH_H

#include "KVStore.h"
#include "kvstore_global_api.h"

constexpr int KEYCODE_LEN = 4;
const char* KEYCODE_STORAGE_KEY = "key";

class Auth {
  private:
  int trueKeycode = 1234;
  void storeKeycode(int code);
  int getKeycode();
  int convertCharToInt(char digit);
  int convertKeycodeToInt(char code[KEYCODE_LEN]);

  public:
  void setup();
  void loadKeycode();
  bool resetKeycode(char code[KEYCODE_LEN]);
  bool checkKeycode(char code[KEYCODE_LEN]);
};

#endif