/*
  Anti-Crook Bag: A secure backpack that alarms as a theft detterent.
  Copyright (C) 2026 Jonas Blackwood, Malachi Oldham, Jesse Sivils

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/* 
  Auth.h
  ---------------------
  Written by Jonas Blackwood
  Some KVStore code generated by ChatGPT
*/

#include "Auth.h"

void Auth::setup() {
  loadKeycode();
}

void Auth::loadKeycode() {
  int keycode = getKeycode();
  Serial.print("AUTH: Loaded Keycode: "); Serial.println(keycode);
  trueKeycode = keycode;
}

// --- Store & Get ---
void Auth::storeKeycode(int code) {
  kv_set(KEYCODE_STORAGE_KEY, &code, sizeof(code), 0);
}

int Auth::getKeycode() {
  int code = 0;
  size_t actual_size;
  kv_get(KEYCODE_STORAGE_KEY, &code, sizeof(code), &actual_size);
  return code;
}

// --- Conversion ---
int Auth::convertCharToInt(char digit) {
  switch (digit) {
    case '0': return 0;
    case '1': return 1;
    case '2': return 2;
    case '3': return 3;
    case '4': return 4;
    case '5': return 5;
    case '6': return 6;
    case '7': return 7;
    case '8': return 8;
    case '9': return 9;
    default:  return -1; // or handle error appropriately
  }
}

int Auth::convertKeycodeToInt(char* charKeycode) {
  int mult = 1;
  int keycode = 0;
  for (int i = 0; i < KEYCODE_LEN; i++) { // Loop backwards to add 10 to the multiplier for each digit
    int digit = convertCharToInt(charKeycode[KEYCODE_LEN-i-1]);
    if (digit < 0) return -1;
    keycode += digit * mult;
    mult *= 10;
  }
  return keycode;
}

// --- Check Keycode ---
bool Auth::checkKeycode(char* charKeycode) {
  int keycode = convertKeycodeToInt(charKeycode);
  if (keycode < 0) {
    Serial.println("Keycode contains letters. Invalid.");
    return 0;
  }
  return keycode == trueKeycode;
}

// --- Reset Keycode ---
bool Auth::resetKeycode(char *charKeycode) {
  int keycode = convertKeycodeToInt(charKeycode);
  if (keycode < 0) return 0;
  Serial.print("AUTH: Storing new keycode: "); Serial.println(keycode);
  storeKeycode(keycode);
  loadKeycode();
  return 1;
}